import "./globals.css";
import React from "react";
import { ThemeProvider } from "@mui/material/styles";
import theme from "./config/theme.js";

export const metadata = {
  title: "My To Dos",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ThemeProvider theme={theme}>{children}</ThemeProvider>
      </body>
    </html>
  );
}
